safe: true
permalink: /:title.html
exclude: [ assets, bem-components-demo, compare ]
markdown: kramdown

default_theme: yandex
default_width: 792
default_lang: ru
default_body_class: list

kramdown:
  enable_coderay: false

presentation:
    title: Генератор сайта для вашей библиотеки блоков
    service: пЯТЬница
    nda: true

author:
    name: Владимир Гриненко
    position: руководитель группы общих компонентов
    company:
        name: Яндекс
        url:  http://yandex.ru/

progress: true
